# Generated by Django 6.0.5 on 2026-05-09 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('work_type', models.CharField(choices=[('farming', '🌾 Farming'), ('construction', '🏗️ Construction'), ('domestic', '🏠 Domestic Help'), ('loading', '🚛 Loading/Unloading'), ('craft', '🎨 Craft & Weaving'), ('carpentry', '🪚 Carpentry'), ('irrigation', '🌱 Irrigation'), ('driving', '🚗 Driving'), ('cooking', '🍳 Cooking'), ('other', '🔧 Other')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('urgent', 'Urgent'), ('filled', 'Filled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workers_needed', models.IntegerField(default=1)),
                ('workers_filled', models.IntegerField(default=0)),
                ('duration', models.CharField(help_text='e.g. 3 days, 2 weeks', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('meals_provided', models.BooleanField(default=False)),
                ('transport_provided', models.BooleanField(default=False)),
                ('tools_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='JobReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobs.job')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job', 'reviewer', 'reviewed_user')},
            },
        ),
    ]
